In [3]:
import numpy as np

In [4]:
#!pip install numpy

In [5]:
my_list=[10,20,30,40]

In [6]:
type(my_list)

list

In [7]:
np.array(my_list)

array([10, 20, 30, 40])

In [8]:
my_numpy_array=np.array(my_list)

In [9]:
type(my_numpy_array)

numpy.ndarray

In [10]:
my_numpy_array.max()

np.int64(40)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.random.random(4)

array([0.31994195, 0.63260366, 0.63694046, 0.01345562])

In [14]:
#array arithmetic

In [15]:
my_list1=[1,2,3,4]

my_list2=[10,20,30,40]

In [16]:
my_list1+my_list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [17]:
my_numpy_array1=np.array(my_list1)

my_numpy_array2=np.array(my_list2)

In [18]:
my_numpy_array1+my_numpy_array2

array([11, 22, 33, 44])

In [19]:
my_numpy_array1*my_numpy_array2

array([ 10,  40,  90, 160])

In [20]:
my_numpy_array1/my_numpy_array2

array([0.1, 0.1, 0.1, 0.1])

In [21]:
other_array=np.array([100,200,300,400])

In [22]:
other_array.min()

np.int64(100)

In [23]:
other_array.sum()

np.int64(1000)

In [24]:
#arrange and indexing

In [25]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np_array=np.arange(0,10)

In [28]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np_array[0]

np.int64(0)

In [31]:
np_array[1:4:]

array([1, 2, 3])

In [32]:
np_array[2:6:2]

array([2, 4])

In [33]:
# random

In [34]:
np.random.randn(4,4)

array([[ 0.27891432, -0.09412649,  0.18861205, -1.39123473],
       [ 1.90657638,  2.02579191, -1.45894702,  0.8951111 ],
       [ 0.05620165,  1.02136661, -0.49085619,  2.3015575 ],
       [-1.00800361,  0.81509704, -0.04424112,  0.94652513]])

In [35]:
np.random.randint(1,300,5)

array([156,   6, 188, 186, 281])