In [16]:
import numpy as np

In [17]:
my_matrix=[[10,15],[20,40]]

In [18]:
my_matrix

[[10, 15], [20, 40]]

In [19]:
# row * column

In [20]:
numpy_matrix=np.array([[5,10],[15,20]])

In [21]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [22]:
numpy_matrix[0,1]

np.int64(10)

In [23]:
numpy_matrix.sum()

np.int64(50)

In [24]:
#matrix arithmetic

In [25]:
first_array=np.array([[10,20],[30,40]])

In [26]:
second_array=np.array([[5,15],[25,35]])

In [27]:
first_array+second_array

array([[15, 35],
       [55, 75]])

In [28]:
first_array

array([[10, 20],
       [30, 40]])

In [29]:
third_array=np.array([[50,60]])

In [30]:
first_array+third_array

array([[ 60,  80],
       [ 80, 100]])

In [32]:
#matrix multiplication

In [33]:
first_array*second_array

array([[  50,  300],
       [ 750, 1400]])

In [34]:
# dot product

In [37]:
first_matrix=np.array([[10,20,30]])

In [38]:
second_matrix=np.array([[2,3],[2,3],[2,3]])

In [43]:
first_matrix.shape

(1, 3)

In [44]:
second_matrix.shape

(3, 2)

In [45]:
result_matrix=first_matrix.dot(second_matrix)

In [46]:
result_matrix

array([[120, 180]])

In [47]:
result_matrix.shape

(1, 2)