In [2]:
import numpy as np

In [3]:
new_array=np.random.randint(1,100,20)

In [4]:
new_array

array([ 7, 33, 81, 23, 55, 52, 51, 30, 12, 79, 20,  3, 58,  5, 98, 36, 15,
       19, 93, 91])

In [5]:
new_array>25

array([False,  True,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True, False,  True,  True, False, False,
        True,  True])

In [6]:
new_array[new_array<25]

array([ 7, 23, 12, 20,  3,  5, 15, 19])

In [7]:
matrix_array=np.array([[10,21],[20,30],[30,40]])

In [8]:
matrix_array

array([[10, 21],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.transpose()

array([[10, 20, 30],
       [21, 30, 40]])

In [11]:
#z-score

In [10]:
data = np.array([10,20,12,13,25,100,105])

In [12]:
# outlier

In [13]:
mean=np.mean(data)

In [14]:
mean

np.float64(40.714285714285715)

In [15]:
std=np.std(data)

In [16]:
std

np.float64(39.38714179495017)

In [17]:
z_score=(data-mean)/std

In [18]:
z_score

array([-0.77980489, -0.52591492, -0.7290269 , -0.7036379 , -0.39896994,
        1.50520478,  1.63214977])

In [19]:
z_score[z_score>1]

array([1.50520478, 1.63214977])

In [20]:
#math questions

In [21]:
#2x + 3y=8 and 5x+7y =19

In [22]:
#coefficient

In [24]:
A=np.array([[2,3],[5,7]])

In [29]:
b=np.array([8,19])

In [30]:
solution=np.linalg.solve(A,b)

In [31]:
solution

array([1., 2.])